apiVersion: apps/v1
kind: Deployment
metadata:
  name: passmaker
  labels:
    app: passmaker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: passmaker
  template:
    metadata:
      labels:
        app: passmaker
    spec:
      containers:
      - name: passmaker
        image: nrdevac1/passmaker:latest
        ports:
        - containerPort: 80
        resources:
          limits: 
            memory: "500Mi"
            cpu: "500m"